config/routes.rb
Rails.application.routes.draw do
  resources :mantenimientos
  get 'home/index'
  get 'home/tcu'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :motors

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: 'motors#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end
end

app/models/mantenimiento.rb
class Mantenimiento < ApplicationRecord
  belongs_to :user
  belongs_to :motor
  validates :type_motor, :type_mantenimiento, :motor_name, :city, :material, 
            :date_mantenimiento, :user_email, :user_id, :motor_id, presence: true
  enum :type_mantenimiento, ['Preventivo', 'Correctivo']
  enum :city, ['Santiago de Chile', 'Temuco', 'Antofagasta']
  enum :material, ['Turbinas', 'Sistemas de ignición', 'Sistemas de combustible']
end

app/controllers/mantenimientos_controller.rb
class MantenimientosController < ApplicationController
  before_action :set_mantenimiento, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action only: [:destroy] do
    authorize_request(["admin"])
  end

  # GET /mantenimientos or /mantenimientos.json
  def index
    @mantenimientos = Mantenimiento.paginate(:page => params[:page], :per_page => 9)
  end

  # GET /mantenimientos/1 or /mantenimientos/1.json
  def show
  end

  # GET /mantenimientos/new
  def new
    @motors = Motor.all
    @mantenimiento = Mantenimiento.new
  end

  # GET /mantenimientos/1/edit
  def edit
    @motors = Motor.all
  end

  # POST /mantenimientos or /mantenimientos.json
  def create
    @motors = Motor.all
    motor_name = params[:mantenimiento][:motor_name]
    motor = Motor.find_by(name: motor_name)

    @mantenimiento = Mantenimiento.new(mantenimiento_params)
    @mantenimiento.motor = motor
    @mantenimiento.type_motor = motor.type_motor
    @mantenimiento.user = current_user
    @mantenimiento.user_email = current_user.email
    @mantenimiento.date_mantenimiento = Date.today

    respond_to do |format|
      if @mantenimiento.save
        format.html { redirect_to mantenimiento_url(@mantenimiento), notice: "Mantenimiento was successfully created." }
        format.json { render :show, status: :created, location: @mantenimiento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mantenimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mantenimientos/1 or /mantenimientos/1.json
  def update
    @motors = Motor.all
    motor_name = params[:mantenimiento][:motor_name]
    motor = Motor.find_by(name: motor_name)

    @mantenimiento.motor = motor
    @mantenimiento.type_motor = motor.type_motor

    respond_to do |format|
      if @mantenimiento.update(mantenimiento_params)
        format.html { redirect_to mantenimiento_url(@mantenimiento), notice: "Mantenimiento was successfully updated." }
        format.json { render :show, status: :ok, location: @mantenimiento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mantenimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mantenimientos/1 or /mantenimientos/1.json
  def destroy
    @mantenimiento.destroy

    respond_to do |format|
      format.html { redirect_to mantenimientos_url, notice: "Mantenimiento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mantenimiento
      @mantenimiento = Mantenimiento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mantenimiento_params
      params.require(:mantenimiento).permit(:type_motor, :type_mantenimiento, :motor_name, :city, :material, :date_mantenimiento, :user_email, :user_id, :motor_id)
    end
end

app/helpers/mantenimientos_helper.rb
module MantenimientosHelper
end

app/views/mantenimientos/_form.html.erb
<%= form_with(model: mantenimiento) do |form| %>
  <% if mantenimiento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mantenimiento.errors.count, "error") %> prohibited this mantenimiento from being saved:</h2>

      <ul>
        <% mantenimiento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if action_name == "edit" %>
    <% if (mantenimiento.motor.photo != '') || mantenimiento.motor.photo.nil? %>
      <%= image_tag mantenimiento.motor.photo, class: 'rounded mx-auto d-block w-25' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4tz_gilgETvc2A7tVnVD_Z72z1_DrqwY00IFji_Q55BG4cTjq0zlIXanmPREaaU0GcY&usqp=CAU', class: 'rounded mx-auto d-block w-25' %>
    <% end %>
  <% end %>

  <div class="input-group py-2">
    <%= form.label :motor_name, "Nombre del Motor", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.select :motor_name, options_for_select(@motors.map { |motor| motor.name }, @mantenimiento.motor_name), {}, class: "form-select" %>
    <%# form.select :motor_name, options_from_collection_for_select(@motors, :id, :name, @mantenimiento.motor_id), {}, class: "form-select" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :type_mantenimiento, "Tipo de mantenimiento", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.select :type_mantenimiento, Mantenimiento.type_mantenimientos.keys, {}, class: "form-select" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :material, "Material", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.select :material, Mantenimiento.materials.keys, {}, class: "form-select" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :city, "Ciudad", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.select :city, Mantenimiento.cities.keys, {}, class: "form-select" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :date_mantenimiento, "Fecha Mantenimiento", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.date_field :date_mantenimiento, placeholder: "Fecha Mantenimiento", class: "form-control" %>
  </div>
  
  <div class="py-2">
    <% if action_name == "new" %>
      <%= form.submit "Guardar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% else %>
      <%= form.submit "Actualizar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% end %>
  </div>
<% end %>

app/views/mantenimientos/_mantenimiento.html.erb
<div id="<%= dom_id mantenimiento %>" class="col-4 py-2">
  <div class="card text-center border-success">
    <% if (mantenimiento.motor.photo != '') || mantenimiento.motor.photo.nil? %>
      <%= image_tag mantenimiento.motor.photo, class: 'card-img-top' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4tz_gilgETvc2A7tVnVD_Z72z1_DrqwY00IFji_Q55BG4cTjq0zlIXanmPREaaU0GcY&usqp=CAU', class: 'card-img-top' %>
    <% end %>
    <div class="card-header">
      <h5 class="card-title fw-bold">
        <%= mantenimiento.motor.type_motor %>
      </h5>
      <p class="card-subtitle">
        Mantenimiento <%= mantenimiento.type_mantenimiento %>
      </p>
    </div>
    <div class="card-body">
      <p class="card-text fst-italic m-0">
        Modelo: <%= mantenimiento.motor.name %>
      </p>
      <% if action_name == 'show' %>
        <p class="card-text fst-italic m-0">
          Material: <%= mantenimiento.material %>
        </p>
        <p class="card-text fst-italic m-0">
          <%= mantenimiento.city %>
        </p>
        <p class="card-text fst-italic m-0">
          <%= mantenimiento.date_mantenimiento.strftime("%d/%m/%Y") %>
        </p>
        <p class="card-text fst-italic m-0">
          <%= mantenimiento.user_email %>
        </p>
      <% end %>
    </div>
    <div class="card-footer">
      <% if action_name == 'index' %>
        <%= link_to mantenimiento do %>
          <i class="bi bi-eye-fill text-primary fs-5"></i>
        <% end %>
      <% else %>
        <div class="d-flex justify-content-around">
          <%= link_to mantenimientos_path do %>
            <i class="bi bi-arrow-return-left text-secondary fs-5 px-1"></i>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <%= link_to edit_mantenimiento_path(mantenimiento) do %>
                <i class="bi bi-pencil-fill text-success fs-5 px-1"></i>
              <% end %>
              <%= button_to @mantenimiento, method: :delete, style: "all: unset; cursor: pointer" do %>
                <i class="bi bi-trash-fill text-danger fs-5 px-1"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/mantenimientos/edit.html.erb
<div class="card p-4">
  <div class="d-flex align-items-center">
    <div class="col-1 px-0" style="width: 35px">
      <%= link_to mantenimientos_path do %>
        <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
      <% end %>
    </div>
    <h1>Editar Mantenimiento</h1>
  </div>

  <%= render "form", mantenimiento: @mantenimiento %>
</div>

app/views/mantenimientos/index.html.erb
<div class="card px-3 pb-5">
  <p style="color: green"><%= notice %></p>

  <div class="container">
    <div class="d-flex justify-content-between align-items-center my-3">
      <h1>Mantenimientos</h1>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to "Crear Nuevo Mantenimiento", new_mantenimiento_path, class: "btn btn-outline-success" %>
        <% end %>
      <% end %>
    </div>
    <div id="mantenimientos">
      <div class="row">
        <% @mantenimientos.each do |mantenimiento| %>
          <%= render mantenimiento %>
        <% end %>
      </div>
    </div>
    <div class="pt-3">
      <%= will_paginate @mantenimientos, list_classes: %w(pagination justify-content-center),
        previous_label: '&laquo;', next_label: '&raquo;', 
        renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  </div>
</div>

app/views/mantenimientos/new.html.erb
<div class="card p-4">
  <div class="d-flex align-items-center">
    <div class="col-1 px-0" style="width: 35px">
      <%= link_to mantenimientos_path do %>
        <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
      <% end %>
    </div>
    <h1>Nuevo Mantenimiento</h1>
  </div>

  <%= render "form", mantenimiento: @mantenimiento %>
</div>

app/views/mantenimientos/show.html.erb
<div class="row">
  <%= render @mantenimiento %>
</div>