config/routes.rb
Rails.application.routes.draw do
  resources :mantenimientos
  get 'home/index'
  get 'home/tcu'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :motors

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: 'motors#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg border-bottom border-3" style="background-color: #fff">
  <div class="container-fluid">
    <img src="https://st3.depositphotos.com/25119998/34747/v/450/depositphotos_347473818-stock-illustration-globe-plane-travel-icon-vector.jpg" height="50">
    <a class="navbar-brand" href="#">
      <%= link_to 'JetMaintain', '/', class: 'navbar-brand' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Motores', motors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mantenimientos', mantenimientos_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Términos y Condiciones', home_tcu_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown dropstart">
          <a class="nav-link dropdown-toggle" href="/" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
              Hola <%= current_user.email %>
            <% else %>
              Registrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li>
                <%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item' , method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item' %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item' %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>