config/routes.rb
Rails.application.routes.draw do
  resources :mantenimientos
  get 'home/index'
  get 'home/tcu'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :motors

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: 'motors#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end
end

app/models/motor.rb
class Motor < ApplicationRecord
  has_many :mantenimiento
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  enum :type_motor, ['Motor a reacción', 'Motor a turbohélice']
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action only: [:destroy] do
    authorize_request(["admin"])
  end

  # GET /motors or /motors.json
  def index
    @motors = Motor.paginate(:page => params[:page], :per_page => 9)
  end

  # GET /motors/1 or /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors or /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully created." }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1 or /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully updated." }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1 or /motors/1.json
  def destroy
    @motor.destroy

    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motor_params
      params.require(:motor).permit(:type_motor, :name, :description, :photo)
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= form_with(model: motor) do |form| %>
  <% if motor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
        <% motor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if action_name == "edit" %>
    <% if (motor.photo != '') || motor.photo.nil? %>
      <%= image_tag motor.photo, class: 'rounded mx-auto d-block w-25' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4tz_gilgETvc2A7tVnVD_Z72z1_DrqwY00IFji_Q55BG4cTjq0zlIXanmPREaaU0GcY&usqp=CAU', class: 'rounded mx-auto d-block w-25' %>
    <% end %>
  <% end %>

  <div class="input-group py-2">
    <%= form.label :name, "Nombre", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_field :name, placeholder: "Nombre", class: "form-control" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :type_motor, "Tipo de Motor", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.select :type_motor, Motor.type_motors.keys, {}, class: "form-select" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :description, "Descripción", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_area :description, placeholder: "Descripción", class: "form-control" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :photo, "Foto URL", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_field :photo, placeholder: "Foto URL", class: "form-control" %>
  </div>
  
  <div class="py-2">
    <% if action_name == "new" %>
      <%= form.submit "Guardar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% else %>
      <%= form.submit "Actualizar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% end %>
  </div>
<% end %>

app/views/motors/_motor.html.erb
<div id="<%= dom_id motor %>" class="col-4 py-2">
  <div class="card text-center border-success">
    <% if (motor.photo != '') || motor.photo.nil? %>
      <%= image_tag motor.photo, class: 'card-img-top' %>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4tz_gilgETvc2A7tVnVD_Z72z1_DrqwY00IFji_Q55BG4cTjq0zlIXanmPREaaU0GcY&usqp=CAU', class: 'card-img-top' %>
    <% end %>
    <div class="card-header">
      <h5 class="card-title fw-bold">
        <%= motor.name %>
      </h5>
      <p class="card-subtitle">
        <%= motor.type_motor %>
      </p>
    </div>
    <div class="card-body">
      <p class="card-text fst-italic">
        <%= motor.description %>
      </p>
    </div>
    <div class="card-footer">
      <% if action_name == 'index' %>
        <%= link_to motor do %>
          <i class="bi bi-eye-fill text-primary fs-5"></i>
        <% end %>
      <% else %>
        <div class="d-flex justify-content-around">
          <%= link_to motors_path do %>
            <i class="bi bi-arrow-return-left text-secondary fs-5 px-1"></i>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <%= link_to edit_motor_path(motor) do %>
                <i class="bi bi-pencil-fill text-success fs-5 px-1"></i>
              <% end %>
              <%= button_to @motor, method: :delete, style: "all: unset; cursor: pointer" do %>
                <i class="bi bi-trash-fill text-danger fs-5 px-1"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/motors/edit.html.erb
<div class="card p-4">
  <div class="d-flex align-items-center">
    <div class="col-1 px-0" style="width: 35px">
      <%= link_to motors_path do %>
        <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
      <% end %>
    </div>
    <h1>Editar Motor</h1>
  </div>

  <%= render "form", motor: @motor %>
</div>

app/views/motors/index.html.erb
<div class="card px-3 pb-5">
  <p style="color: green"><%= notice %></p>

  <div class="container">
    <div class="d-flex justify-content-between align-items-center my-3">
      <h1>Motores</h1>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to "Crear Nuevo Motor", new_motor_path, class: "btn btn-outline-success" %>
        <% end %>
      <% end %>
    </div>
    <div id="motors">
      <div class="row">
        <% @motors.each do |motor| %>
          <%= render motor %>
        <% end %>
      </div>
    </div>
    <div class="pt-3">
      <%= will_paginate @motors, list_classes: %w(pagination justify-content-center),
        previous_label: '&laquo;', next_label: '&raquo;', 
        renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  </div>
</div>

app/views/motors/new.html.erb
<div class="card p-4">
  <div class="d-flex align-items-center">
    <div class="col-1 px-0" style="width: 35px">
      <%= link_to motors_path do %>
        <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
      <% end %>
    </div>
    <h1>Nuevo Motor</h1>
  </div>

  <%= render "form", motor: @motor %>
</div>

app/views/motors/show.html.erb
<div class="row">
  <%= render @motor %>
</div>